# configs/train_hyp.yaml

#path model
model: weights/yolov8n.pt  # train lại đổi model thành cái cuối là last.pt
data: vehicle.yaml
project: result/
name: traffic_detector

# thêm này nếu muốn train lại
#resume: True

# Hyperparameters
epochs: 100
imgsz: 960
batch: 4
device: 0
workers: 2
amp: False
cache: True
rect: True
patience: 20
plots: True

# Optimizer
optimizer: AdamW
lr0: 0.001
weight_decay: 0.0005

# Augmentation
mosaic: 0.5
mixup: 0.1
fliplr: 0.5
degrees: 0